#!/bin/sh -f

# Copyright (C) 2018, Guy Barrand. All rights reserved.
# See the file gopaw.license for terms.

#
#  ./run 
#  ./run -pawex2
#  ./run -pawex2
#  ./run -dir_users -kumac_file=opaw_murban_fig.kumac1
#  ./run -dir_PAW_cpp_root -all
#
# used in softinex/mgr/one_exec :
#  ./run -dir_PAW_cpp_root -all -out
#  ./run -dir_PAW_py_root  -all -out
#  ./run -dir_users        -all -out
#  ./run -dir_gopaw        -all -out
#

bush_home=`dirname $0`/../../bush

save_dir=`pwd`

version="`${bush_home}/app_vers`"
#pack=`${bush_home}/app_name`

# for softinex/mgr/one_exec :
run_out=
#run_out_dir="${save_dir}/ref/."
run_out_dir="${save_dir}/."

run_args=
build_args=

run_all=no
run_kumac=
run_dir=PAW_cpp_root

while test $# -ge 1 ; do
  case $1 in
    -x)       build_args="${build_args} $1";;

    # local options : 
    -all)     run_all=yes;;
    -out)     run_out=yes;;
    -dir_*)   run_dir="`echo $1 | sed -e 's:\-dir_::g'`";;
    -pawex*)  run_kumac="pawex`echo $1 | sed -e 's:\-pawex::g'`.kumac";;

    -*) run_args="${run_args} $1";;  
     *) run_args="${run_args} $1";;  
  esac
  shift
done

. ${bush_home}/ourex_header # to get build_path

save_dir="`pwd`"

#//////////////////////////////////////////
#//////////////////////////////////////////
#//////////////////////////////////////////

#build_path=${save_dir}/${build_dir}
#paw_exe=${build_path}/gopaw
distrib_dir=${save_dir}/${build_dir}/distrib/gopaw/${version}

paw_exe=${distrib_dir}/bin/gopaw

if [ ! -x ${paw_exe} ] ; then
  echo "${paw_exe} not found."
  exit
fi

if [ ! -d ../examples/${run_dir} ] ; then
  echo "directory ../examples/${run_dir} not found."
  exit
fi

./clean_exas
cd ../examples/${run_dir}

LC_CTYPE=C;export LC_CTYPE

# PAW> exec pawex1
# PAW> lcd $GOPAWROOT/examples/PAW_cpp_root
# PAW> exec all

if [ "${run_all}" = "yes" ] ; then
  if [ ! -e all.kumac ] ; then
    echo "file all.kumac not found."
    exit
  fi	
  items="`grep exec all.kumac | awk '{print $2}'`"
  for item in ${items} ; do
    echo "${item} ..."
    name="`echo ${item} | sed -e 's:.kumac::g'`"
    if [ "${run_out}" = "yes" ] ; then
      out_file="out_${run_dir}_${name}.ps"
      ${paw_exe} ${run_args} -offscreen -out=${out_file} -format=INZB_PS ${name}.kumac
      /bin/mv ${out_file} ${run_out_dir}/.

      out_file="out_${run_dir}_${name}.png"
      ${paw_exe} ${run_args} -offscreen -out=${out_file} -format=INZB_PNG ${name}.kumac
      /bin/mv ${out_file} ${run_out_dir}/.
    else
      ${paw_exe} ${run_args} ${name}.kumac
    fi    
  done

else
  if [ "${run_kumac}" = "" ] ; then
    ${paw_exe} ${run_args}
  else
    ${paw_exe} -kumac_file=${run_kumac} ${run_args}
  fi
fi

cd ${save_dir}
./clean_exas

