#!/bin/sh -f

# Copyright (C) 2018, Guy Barrand. All rights reserved.
# See the file gopaw.license for terms.

inlib_home=../../inexlib/inlib

c++ -o ./wrap_exe -I${inlib_home} ${inlib_home}/apps/wrap.cpp
use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi

#wrap_exe=_wrap
#./check_app _wrap '_wrap program not found.'
#use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi

find ../source -name 'wrap_*' -exec /bin/rm -f {} \;

find ../scripts/help -name '*.help' -print > tmp_0
for file in $(cat tmp_0) ; do
  name=`basename ${file}`
  name=`echo ${name} | sed -e 's:\.:\_:g' | sed -e 's:\-:\_:g'`
  #echo "${name}"
  ./wrap_exe ${file} ../source/wrap_${name}
done
/bin/rm -f tmp_0
/bin/rm -f wrap_exe
