#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file gopaw.license for terms.

bush_home=.

items="PAW_cpp_root PAW_f77_hbook PAW_py_root users gopaw"

for item in ${items} ; do
  ${bush_home}/find_rm ../../examples/${item} 'gopaw_*_wrap_*.cpp'
  ${bush_home}/find_rm ../../examples/${item} 'gopaw_f77_new_*.f'
  ${bush_home}/find_rm ../../examples/${item} '*.bundle'
  ${bush_home}/find_rm ../../examples/${item} '*.so'
  ${bush_home}/find_rm ../../examples/${item} '*.dll'
  ${bush_home}/find_rm ../../examples/${item} '*.lib'
  ${bush_home}/find_rm ../../examples/${item} 'term.hist'
  ${bush_home}/find_rm ../../examples/${item} '*.pyc'
  ${bush_home}/find_rm ../../examples/${item} '*.ps'
  ${bush_home}/find_rm ../../examples/${item} '*.eps'
  ${bush_home}/find_rm ../../examples/${item} 'vx.*'
  ${bush_home}/find_rm ../../examples/${item} 'vx_gl.*'
  ${bush_home}/find_rm ../../examples/${item} 'last.kumac*'
done

/bin/rm -f ../../examples/users/out.dat

${bush_home}/find_rm ../../examples/PAW_py_root '*.root'
${bush_home}/find_rm ../../examples/PAW_py_root 'vector.data'
${bush_home}/find_rm ../../examples/PAW_cpp_root '*.root'
${bush_home}/find_rm ../../examples/PAW_cpp_root 'vector.data'


